### ISSUE TITLE
Doesn't Generate Multiple Inheritance for Classes

### ISSUE THREAD

**Issue by sdgirard** [bafolts/tplant#10]
[autos.zip](https://github.com/bafolts/tplant/files/2921271/autos.zip)

The supplied file doesn't generate correctly because of multiple inheritance when using Interfaces.

**Comment by bafolts** [comment]
There is a pull request in place for this https://github.com/bafolts/tplant/pull/11. The fix will go in 2.0.3 once merged.

**Comment by sdgirard** [comment]
Excellent... will look forward for the update

Thanks

**Comment by bafolts** [comment]
This is fixed in 2.0.3
