### ISSUE TITLE
tplant 3.1.0 doesn't support Typescript 4.7's "moduleResolution": "Node16" 

### ISSUE THREAD

**Issue by ClementValot** [bafolts/tplant#100]
#### Describe the bug

 - Node.js version: 16.15.0
 - OS & version: Windows 11

#### Actual behavior

Using tplant CLI with Typescript 4.7 and moduleResolution="Node16" raises the following error:
```
   Error: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node12', 'nodenext'.
```

#### Code to reproduce

package.json
```json
{
  "name": "tplant-node16-bug",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "uml": "tplant -i src/**/*.ts -o diagram.puml"
  }
  "devDependencies": {
    "tplant": "^3.1.0",
    "typescript": "^4.7.4"
  }
}
```
tsconfig.json
```json
{
  "compilerOptions": {
    "module": "Node16",
    "moduleResolution": "Node16",
    "target": "es6",
  },
  "exclude": [
    "node_modules"
  ]
}
```

"moduleResolution": "Node16" is [required](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1128910470) for Typescript 4.7 support of the exports field in package.json

**Comment by bafolts** [comment]
I can't recreate this problem with node 16.15.0 on macOS using the provided steps. It doesn't seem to be an issue with `tplant` unless the code to reproduce is modifying this [tsconfig.json](https://github.com/bafolts/tplant/blob/master/tsconfig.json). Taking a shot in the dark at what the problem might be, [perhaps it is `node16` and not `Node16`](https://github.com/microsoft/TypeScript/issues/48646#issuecomment-1116760128)?
