### ISSUE TITLE
Error on install "The engine "node" is incompatible with this module. Expected version "^16.0.0". Got "18.16.1"

### ISSUE THREAD

**Issue by EmilianoCagliari** [bafolts/tplant#119]
Describe the bug
Nest.js version: v10.0.3
Node.js Version: v18.16.1

OS & version: MacOs

Actual behavior
Im trying to add tplant with yarn and i get 

yarn global add tplant                    
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error tplant@3.1.2: The engine "node" is incompatible with this module. Expected version "^16.0.0". Got "18.16.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by bafolts** [comment]
I fixed this in the engines field. Should be good as of version 3.1.3
