### ISSUE TITLE
overloaded methods/functions are exported incorrectly

### ISSUE THREAD

**Issue by Plagiatus** [bafolts/tplant#18]
I know overloading is a rather rare (and kinda hacky) thing in Typescript, but [still a thing that exists](https://www.typescriptlang.org/docs/handbook/functions.html#Overloads). At the moment, those functions will be exported incorrectly by tplant.

Example ts
```typescript
export class Test {
	move(dx: number, dy: number): string;
	move(v: Vector2): string;
	move(vordx: number | Vector2, dy?: number): string {
		return "just a test";
	}
}
export class Vector2{
	public x: number;
	public y: number;
}
```

What it currently looks like
```puml
@startuml
class Test {
    +move(): dx: number, dy: number): string; (v: Vector2): string; }
}
class Vector2 {
    +x: number
    +y: number
}
@enduml
```

What it should look like
```puml
@startuml
class Test {
    +move(dx: number, dy: number): string
    +move(v: Vector2): string
}
class Vector2 {
    +x: number
    +y: number
}
@enduml
```

**Comment by bafolts** [comment]
A fix for this is in `master` with
https://github.com/bafolts/tplant/commit/11d90e7afc2bae382b29ae7ff5f53434a16a6c47

and will be in 2.0.5
