### ISSUE TITLE
Not working, just error messages

### ISSUE THREAD

**Issue by David-Else** [bafolts/tplant#35]
If I install globally or locally via NPM I just get:
```
/usr/bin/tplant: line 1: use strict: command not found
/usr/bin/tplant: line 2: syntax error near unexpected token `('
/usr/bin/tplant: line 2: `var __importDefault = (this && this.__importDefault) || function (mod) {'
```
If I just type `tplant` or use `tplant --input app.ts --output uml.puml`

version 2.2, Fedora 29 Linux, Node 12.1.0
(an older version of tplant worked fine, I filed another issues a while ago)

**Comment by marcosvrs** [comment]
Fixed in version 2.2.1.
Thanks for the feedback.
