### ISSUE TITLE
Need a way to specify the output format.

### ISSUE THREAD

**Issue by bafolts** [bafolts/tplant#4]
A way to specify the output format should be added. The current default of always writing to STDOUT wont work for all cases.

**Comment by JimTheMan** [comment]
yeah this would be nice. I was able to create a file like this:

`./tplant.js -i ~/Git-Projects/t2-2/t2/CypherApp/src/app/auth-juggler.service.ts > ~/Git-Projects/t2-2/t2/CypherApp/src/app/auth-juggler.service.puml`

but it would be nice to just do this:
`./tplant.js -io ~/Git-Projects/t2-2/t2/CypherApp/src/app/auth-juggler.service.ts`

:)

**Comment by marcosvrs** [comment]
Published.
