### ISSUE TITLE
Broken .png files.

### ISSUE THREAD

**Issue by David-Else** [bafolts/tplant#40]
Hi,

Today I tried to create a .png file twice and both times they came back corrupted and unable to display. File length 111.2 kB. The .svg is still working fine.
```
"uml": "tplant --input src/app.ts --output uml-diagram.png"
```
( tplant --version 2.3.0 )

**Comment by JDThralls** [comment]
This problem still exists, but now it's the same for SVG files as well.
Reading the png file as UTF8 without BOM gives some more information as the file is an error page returned by the server:
```HTML
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /plantuml/png/[hash removed]
on this server.<br />
</p>
</body></html>
```

**Comment by bafolts** [comment]
This is attempting to hit `plantuml.com/plantuml/png/[hash]`. This must have started failing requests. 

https://github.com/bafolts/tplant/blob/master/src/index.ts#L138

Will need a different mechanism to generate these images.

**Comment by bafolts** [comment]
I am guessing we ended up hitting a server running.

https://www.npmjs.com/package/node-plantuml

Most likely need to update this tool to use that package when generating the image.

**Comment by mbnoimi** [comment]
Still occurs in `tplant version 2.3.3`

**Comment by lcy19** [comment]
Still occurs in tplant version 3.1.0, any suggestions?

**Comment by bafolts** [comment]
Has been no fix to this. We still rely on the hosted file server. Will need an update to generate the images locally.

**Comment by bafolts** [comment]
@lcy19 can you test #102 ? That will generate the images locally and no longer depend on the server. Anyone else in this thread can feel free to test the PR on their machine then I will merge and push new version.

**Comment by lcy19** [comment]
@bafolts Thanks for your work. I tried in Mac mini (M1, 2020), it works for svg and puml,but png is still not work. I'm not sure the way I test whether is right. First download [your code](https://github.com/bafolts/tplant/tree/bafolts/issue-40), then 
```shell
npm install
npm run build
```
and then using `index.js` in dist folder. The test files are [livekit/server-sdk-js](https://github.com/livekit/server-sdk-js),and test commands are
```shell
node ./index.js -i server-sdk-js/src/**/*.ts -o tmp.png
```

**Comment by bafolts** [comment]
The way you tested is right. If you open tmp.png does it have image of an error?

**Comment by lcy19** [comment]
yes, using vscode to open it and error like this
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/55749957/222297265-44a67590-be9d-4e2b-b6de-4da597935615.png">

BTW, when I run `npm install`, it reports some error, so using `npm install --force`
<img width="635" alt="image" src="https://user-images.githubusercontent.com/55749957/222297644-18bcd023-187e-4090-a3e8-f9deaa83451d.png">

I'm not sure whether this problem is about node version, my using node version is v16.15.1
