### ISSUE TITLE
Missing Aggregation/Composition feature

### ISSUE THREAD

**Issue by ThePlenkov** [bafolts/tplant#48]
Hi! First of all I would like to express great admire to this idea. 

It's so simple and implementation is perfect.

However I would like to have some feature which I wish to have in my diagram.

Sometimes we have classes which have instances of another classes. So it's not inheritance but another way of relationship.

How about the idea to invent pseudo comment (may be TSDoc) in ts file declaring that a specific attribute is a relationship in fact: aggregation or composition? Or at least by default all kinds of attributes with references to interfaces/classes include with aggregation by default?

Thank you!

**Comment by iiian** [comment]
Agree, would also like this feature. Any suggestions on how to contribute?

**Comment by bafolts** [comment]
If you were to invent some comment tag it should be straight forward to parse that tag. Would something similar to:

```
@aggregates Class1, Class2, Class3
```

work easy enough?

**Comment by esmiralha** [comment]
I believe this should work without a comment or decorator. Inspect the members of the class and create relationships for those who point to user-defined types (classes, interfaces, etc.).
