### ISSUE TITLE
Problem parsing namespaces

### ISSUE THREAD

**Issue by rugoncalves** [bafolts/tplant#81]
`Problem` 
When a namespace defines several namespaces, the output file is just the first namespace, and everything else is ignored.

`Scenario`
Imagine defining a namespace that contains other namespaces until it has the class:

```
namespace very.special {
  export class Greeter {
    greeting: string;
    prefix: string = "Hello, ";
    constructor(message: string) {
      this.greeting = message;
    }
    set prefix(prefix: string) {
      this.prefix = prefix;
    }
    greet(prefix: string = "Foo"): string;
    greet(): string {
      return this.prefix + this.greeting;
    }
  }
}
```

When running the command line:
`tplant --input test/Playground/Classes/*.ts --output test/Playground/testmultinamespace.svg`

The output is the following:
![image](https://user-images.githubusercontent.com/10534623/140088934-20692788-065e-4afd-953a-05a3cde33708.png)

All the code that is analyzed before this pattern gets added to the SVG, but after this pattern, nothing else is added.

**Comment by bafolts** [comment]
What is the expected output with this input? I believe the issue here is the period is unexpected in the namespace name.

**Comment by rugoncalves** [comment]
The expected output is the same as the output of the non-abbreviated form:

```
namespace very {
  namespace special {
    export class Greeter {
      greeting: string;
      prefix: string = "Hello, ";
      constructor(message: string) {
        this.greeting = message;
      }
      set prefix(prefix: string) {
        this.prefix = prefix;
      }
      greet(prefix: string = "Foo"): string;
      greet(): string {
        return this.prefix + this.greeting;
      }
    }
  }
}
```

That is:
![image](https://user-images.githubusercontent.com/10534623/140274418-2cd5160a-f451-4d5a-8c90-9e7ef0218333.png)

Thank you for the quick reply!
